// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi casa

    Schemes:
      http
    Host: tobedecided
    BasePath: /v1
    Version: 1.0.0
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
    Contact: <mange_magnusson@hotmail.com>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
