// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "casa",
    "contact": {
      "email": "mange_magnusson@hotmail.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "host": "tobedecided",
  "basePath": "/v1",
  "paths": {
    "/alarms": {
      "get": {
        "tags": [
          "alarms"
        ],
        "summary": "Gets all alarms",
        "operationId": "listAlarms",
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "$ref": "#/definitions/alarms"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "alarms"
        ],
        "summary": "Create/Update the alarm",
        "operationId": "createAlarm",
        "parameters": [
          {
            "description": "Crete a new alarm",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/createAlarm"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Ok",
            "headers": {
              "Access-Control-Allow-Origin": {
                "type": "string",
                "default": "*",
                "description": "Allow access control"
              }
            }
          },
          "405": {
            "description": "Invalid input"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/alarms/{alarmId}/alerts": {
      "get": {
        "tags": [
          "alerts"
        ],
        "summary": "Gets all alerts for the alarm",
        "operationId": "listAlertsForAlarm",
        "parameters": [
          {
            "type": "string",
            "description": "Id of the alarm",
            "name": "alarmId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "$ref": "#/definitions/alerts"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/alarms/{alarmId}/alerts/{id}": {
      "get": {
        "tags": [
          "alerts"
        ],
        "summary": "Get alerts for the specified id",
        "operationId": "listAlertsById",
        "parameters": [
          {
            "type": "string",
            "description": "Id of the alarm",
            "name": "alarmId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "Id of the alert",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "$ref": "#/definitions/alerts"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "alerts"
        ],
        "summary": "Alert about something",
        "operationId": "addAlert",
        "parameters": [
          {
            "type": "string",
            "description": "Id of the alarm",
            "name": "alarmId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "Id of the alert",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/addAlert"
            }
          }
        ],
        "responses": {
          "405": {
            "description": "Invalid input"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/alarms/{id}": {
      "get": {
        "tags": [
          "alarms"
        ],
        "summary": "Get the alarm",
        "operationId": "getAlarm",
        "parameters": [
          {
            "type": "string",
            "description": "Id of the alarm",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "$ref": "#/definitions/alarm"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "alarms"
        ],
        "summary": "Delete the alarm",
        "operationId": "deleteAlarm",
        "parameters": [
          {
            "type": "string",
            "description": "Id of the alarm",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "Ok"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/alarms/{id}/toggle/": {
      "get": {
        "tags": [
          "alarms"
        ],
        "summary": "List togglings",
        "operationId": "listAlarmLogs",
        "parameters": [
          {
            "type": "string",
            "description": "Id of the alarm",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "$ref": "#/definitions/toggleAlarms"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "alarms"
        ],
        "summary": "Toggle the alarm",
        "operationId": "toggleAlarm",
        "parameters": [
          {
            "type": "string",
            "description": "Id of the alarm",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "Toggle alarm",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/setToggleAlarm"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Ok",
            "schema": {
              "$ref": "#/definitions/toggleAlarm"
            },
            "headers": {
              "Access-Control-Allow-Origin": {
                "type": "string",
                "default": "*",
                "description": "Allow access control"
              }
            }
          },
          "405": {
            "description": "Invalid input"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/alerts": {
      "get": {
        "tags": [
          "alerts"
        ],
        "summary": "Gets all alerts",
        "operationId": "listAlerts",
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "$ref": "#/definitions/alerts"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/devices": {
      "get": {
        "tags": [
          "devices"
        ],
        "summary": "List of added devices",
        "operationId": "listOfDevices",
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "$ref": "#/definitions/devices"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "devices"
        ],
        "summary": "Add a device",
        "operationId": "addDevice",
        "parameters": [
          {
            "description": "Toggle alarms",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/addDevice"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "ok"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/devices/{id}": {
      "delete": {
        "tags": [
          "devices"
        ],
        "summary": "Delete device",
        "operationId": "deleteDevice",
        "parameters": [
          {
            "type": "string",
            "description": "Id of the device",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "ok"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/discovery": {
      "get": {
        "tags": [
          "discovery"
        ],
        "summary": "List discovered Axis devices",
        "operationId": "listDiscoveredCameras",
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "$ref": "#/definitions/discoveredDevices"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "discovery"
        ],
        "summary": "Discover Axis devices",
        "operationId": "newDiscovery",
        "responses": {
          "200": {
            "description": "ok"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/discovery/devices/{serialNumber}/credentials": {
      "post": {
        "tags": [
          "discovery"
        ],
        "summary": "Discover Axis devices",
        "operationId": "setDeviceCredentialsForDiscovery",
        "parameters": [
          {
            "type": "string",
            "description": "The serialNumber of the device.",
            "name": "serialNumber",
            "in": "path",
            "required": true
          },
          {
            "description": "Sets credentials for a discovered device",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/credentials"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "ok"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not found"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "addAlert": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "shortDescription": {
          "type": "string"
        }
      }
    },
    "addDevice": {
      "type": "object",
      "properties": {
        "address": {
          "type": "string"
        },
        "credentials": {
          "$ref": "#/definitions/credentials"
        },
        "serialNumber": {
          "type": "string"
        }
      }
    },
    "alarm": {
      "type": "object",
      "properties": {
        "continous": {
          "type": "boolean"
        },
        "date": {
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "type": "string"
        },
        "devices": {
          "description": "Array of serial numbers",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "string"
        },
        "motionDetection": {
          "type": "boolean"
        },
        "on": {
          "type": "boolean"
        },
        "sms": {
          "$ref": "#/definitions/sms"
        }
      }
    },
    "alarms": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/alarm"
      }
    },
    "alert": {
      "type": "object",
      "properties": {
        "alarmId": {
          "type": "string"
        },
        "date": {
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "shortDescription": {
          "type": "string"
        }
      }
    },
    "alerts": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/alert"
      }
    },
    "createAlarm": {
      "type": "object",
      "properties": {
        "continous": {
          "type": "boolean"
        },
        "description": {
          "type": "string"
        },
        "devices": {
          "description": "Array of serial numbers",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "string"
        },
        "motionDetection": {
          "type": "boolean"
        },
        "sms": {
          "$ref": "#/definitions/sms"
        }
      }
    },
    "credentials": {
      "type": "object",
      "properties": {
        "password": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "device": {
      "type": "object",
      "properties": {
        "address": {
          "type": "string"
        },
        "model": {
          "type": "string"
        },
        "serialNumber": {
          "type": "string"
        },
        "snapshotUrl": {
          "type": "string"
        },
        "status": {
          "$ref": "#/definitions/deviceStatus"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "deviceStatus": {
      "type": "object",
      "properties": {
        "credential": {
          "type": "boolean"
        },
        "error": {
          "type": "boolean"
        },
        "hasStatus": {
          "type": "boolean"
        },
        "lastStatusCheck": {
          "type": "string",
          "format": "date-time"
        },
        "message": {
          "type": "string"
        },
        "network": {
          "type": "boolean"
        },
        "statusCode": {
          "type": "number",
          "format": "integer"
        }
      }
    },
    "devices": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/device"
      }
    },
    "discoveredDevice": {
      "type": "object",
      "properties": {
        "address": {
          "type": "string"
        },
        "lastDiscovered": {
          "type": "string",
          "format": "date-time"
        },
        "model": {
          "type": "string"
        },
        "modelNumber": {
          "type": "string"
        },
        "serialNumber": {
          "type": "string"
        },
        "status": {
          "$ref": "#/definitions/deviceStatus"
        }
      }
    },
    "discoveredDevices": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/discoveredDevice"
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "setToggleAlarm": {
      "type": "object",
      "properties": {
        "on": {
          "type": "boolean"
        }
      }
    },
    "sms": {
      "description": "sms notification",
      "type": "object",
      "properties": {
        "fromNumber": {
          "type": "string"
        },
        "interval": {
          "description": "Number of minutes between sms if alerts keep repeating.",
          "type": "number"
        },
        "mobileNumbers": {
          "description": "Array of mobile numbers",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "password": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "toggleAlarm": {
      "type": "object",
      "properties": {
        "alarmId": {
          "type": "string"
        },
        "date": {
          "type": "string",
          "format": "date-time"
        },
        "on": {
          "type": "boolean"
        }
      }
    },
    "toggleAlarms": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/toggleAlarm"
      }
    }
  }
}`))
}
