apiVersion: v1
kind: Service
metadata:
  name: grpc-casa
spec:
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    app: grpc-casa
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grpc-casa
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grpc-casa
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "-P", "9000",
          "-a", "grpc://127.0.0.1:50051",
          "-s", "hellogrpc.endpoints.safeathome-213613.cloud.goog", # replace <YOUR_PROJECT_ID>
          "--rollout_strategy", "managed",
        ]
        ports:
          - containerPort: 9000
      - name: echo
        image: gcr.io/safeathome-213613/grpc-casa:1.0 # replace <YOUR_PROJECT_ID>
        ports:
          - containerPort: 50051