// Code generated by go-swagger; DO NOT EDIT.

package discovery

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"casa/src/server/models"
)

// ListDiscoveredCamerasOKCode is the HTTP code returned for type ListDiscoveredCamerasOK
const ListDiscoveredCamerasOKCode int = 200

/*ListDiscoveredCamerasOK ok

swagger:response listDiscoveredCamerasOK
*/
type ListDiscoveredCamerasOK struct {

	/*
	  In: Body
	*/
	Payload models.DiscoveredDevices `json:"body,omitempty"`
}

// NewListDiscoveredCamerasOK creates ListDiscoveredCamerasOK with default headers values
func NewListDiscoveredCamerasOK() *ListDiscoveredCamerasOK {
	return &ListDiscoveredCamerasOK{}
}

// WithPayload adds the payload to the list discovered cameras o k response
func (o *ListDiscoveredCamerasOK) WithPayload(payload models.DiscoveredDevices) *ListDiscoveredCamerasOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list discovered cameras o k response
func (o *ListDiscoveredCamerasOK) SetPayload(payload models.DiscoveredDevices) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListDiscoveredCamerasOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.DiscoveredDevices, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*ListDiscoveredCamerasDefault error

swagger:response listDiscoveredCamerasDefault
*/
type ListDiscoveredCamerasDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListDiscoveredCamerasDefault creates ListDiscoveredCamerasDefault with default headers values
func NewListDiscoveredCamerasDefault(code int) *ListDiscoveredCamerasDefault {
	if code <= 0 {
		code = 500
	}

	return &ListDiscoveredCamerasDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list discovered cameras default response
func (o *ListDiscoveredCamerasDefault) WithStatusCode(code int) *ListDiscoveredCamerasDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list discovered cameras default response
func (o *ListDiscoveredCamerasDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list discovered cameras default response
func (o *ListDiscoveredCamerasDefault) WithPayload(payload *models.Error) *ListDiscoveredCamerasDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list discovered cameras default response
func (o *ListDiscoveredCamerasDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListDiscoveredCamerasDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
