// Code generated by go-swagger; DO NOT EDIT.

package discovery

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NewDiscoveryHandlerFunc turns a function with the right signature into a new discovery handler
type NewDiscoveryHandlerFunc func(NewDiscoveryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NewDiscoveryHandlerFunc) Handle(params NewDiscoveryParams) middleware.Responder {
	return fn(params)
}

// NewDiscoveryHandler interface for that can handle valid new discovery params
type NewDiscoveryHandler interface {
	Handle(NewDiscoveryParams) middleware.Responder
}

// NewNewDiscovery creates a new http.Handler for the new discovery operation
func NewNewDiscovery(ctx *middleware.Context, handler NewDiscoveryHandler) *NewDiscovery {
	return &NewDiscovery{Context: ctx, Handler: handler}
}

/*NewDiscovery swagger:route POST /discovery discovery newDiscovery

Discover Axis devices

*/
type NewDiscovery struct {
	Context *middleware.Context
	Handler NewDiscoveryHandler
}

func (o *NewDiscovery) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNewDiscoveryParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
