// Code generated by go-swagger; DO NOT EDIT.

package discovery

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	"casa/src/server/models"
)

// NewSetDeviceCredentialsForDiscoveryParams creates a new SetDeviceCredentialsForDiscoveryParams object
// with the default values initialized.
func NewSetDeviceCredentialsForDiscoveryParams() SetDeviceCredentialsForDiscoveryParams {
	var ()
	return SetDeviceCredentialsForDiscoveryParams{}
}

// SetDeviceCredentialsForDiscoveryParams contains all the bound params for the set device credentials for discovery operation
// typically these are obtained from a http.Request
//
// swagger:parameters setDeviceCredentialsForDiscovery
type SetDeviceCredentialsForDiscoveryParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*Sets credentials for a discovered device
	  Required: true
	  In: body
	*/
	Body *models.Credentials
	/*The serialNumber of the device.
	  Required: true
	  In: path
	*/
	SerialNumber string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *SetDeviceCredentialsForDiscoveryParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Credentials
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body"))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}

	} else {
		res = append(res, errors.Required("body", "body"))
	}

	rSerialNumber, rhkSerialNumber, _ := route.Params.GetOK("serialNumber")
	if err := o.bindSerialNumber(rSerialNumber, rhkSerialNumber, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SetDeviceCredentialsForDiscoveryParams) bindSerialNumber(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.SerialNumber = raw

	return nil
}
