// Code generated by go-swagger; DO NOT EDIT.

package alarms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"casa/src/server/models"
)

// CreateAlarmCreatedCode is the HTTP code returned for type CreateAlarmCreated
const CreateAlarmCreatedCode int = 201

/*CreateAlarmCreated Ok

swagger:response createAlarmCreated
*/
type CreateAlarmCreated struct {
	/*Allow access control
	  Required: true
	  Default: "*"
	*/
	AccessControlAllowOrigin string `json:"Access-Control-Allow-Origin"`
}

// NewCreateAlarmCreated creates CreateAlarmCreated with default headers values
func NewCreateAlarmCreated() *CreateAlarmCreated {
	return &CreateAlarmCreated{
		AccessControlAllowOrigin: "*",
	}
}

// WithAccessControlAllowOrigin adds the accessControlAllowOrigin to the create alarm created response
func (o *CreateAlarmCreated) WithAccessControlAllowOrigin(accessControlAllowOrigin string) *CreateAlarmCreated {
	o.AccessControlAllowOrigin = accessControlAllowOrigin
	return o
}

// SetAccessControlAllowOrigin sets the accessControlAllowOrigin to the create alarm created response
func (o *CreateAlarmCreated) SetAccessControlAllowOrigin(accessControlAllowOrigin string) {
	o.AccessControlAllowOrigin = accessControlAllowOrigin
}

// WriteResponse to the client
func (o *CreateAlarmCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Access-Control-Allow-Origin

	accessControlAllowOrigin := o.AccessControlAllowOrigin
	if accessControlAllowOrigin != "" {
		rw.Header().Set("Access-Control-Allow-Origin", accessControlAllowOrigin)
	}

	rw.WriteHeader(201)
}

// CreateAlarmMethodNotAllowedCode is the HTTP code returned for type CreateAlarmMethodNotAllowed
const CreateAlarmMethodNotAllowedCode int = 405

/*CreateAlarmMethodNotAllowed Invalid input

swagger:response createAlarmMethodNotAllowed
*/
type CreateAlarmMethodNotAllowed struct {
}

// NewCreateAlarmMethodNotAllowed creates CreateAlarmMethodNotAllowed with default headers values
func NewCreateAlarmMethodNotAllowed() *CreateAlarmMethodNotAllowed {
	return &CreateAlarmMethodNotAllowed{}
}

// WriteResponse to the client
func (o *CreateAlarmMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
}

/*CreateAlarmDefault error

swagger:response createAlarmDefault
*/
type CreateAlarmDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateAlarmDefault creates CreateAlarmDefault with default headers values
func NewCreateAlarmDefault(code int) *CreateAlarmDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateAlarmDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create alarm default response
func (o *CreateAlarmDefault) WithStatusCode(code int) *CreateAlarmDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create alarm default response
func (o *CreateAlarmDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create alarm default response
func (o *CreateAlarmDefault) WithPayload(payload *models.Error) *CreateAlarmDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create alarm default response
func (o *CreateAlarmDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAlarmDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
