// Code generated by go-swagger; DO NOT EDIT.

package alarms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAlarmHandlerFunc turns a function with the right signature into a get alarm handler
type GetAlarmHandlerFunc func(GetAlarmParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAlarmHandlerFunc) Handle(params GetAlarmParams) middleware.Responder {
	return fn(params)
}

// GetAlarmHandler interface for that can handle valid get alarm params
type GetAlarmHandler interface {
	Handle(GetAlarmParams) middleware.Responder
}

// NewGetAlarm creates a new http.Handler for the get alarm operation
func NewGetAlarm(ctx *middleware.Context, handler GetAlarmHandler) *GetAlarm {
	return &GetAlarm{Context: ctx, Handler: handler}
}

/*GetAlarm swagger:route GET /alarms/{id} alarms getAlarm

Get the alarm

*/
type GetAlarm struct {
	Context *middleware.Context
	Handler GetAlarmHandler
}

func (o *GetAlarm) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAlarmParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
