// Code generated by go-swagger; DO NOT EDIT.

package alarms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAlarmLogsHandlerFunc turns a function with the right signature into a get alarm logs handler
type GetAlarmLogsHandlerFunc func(GetAlarmLogsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAlarmLogsHandlerFunc) Handle(params GetAlarmLogsParams) middleware.Responder {
	return fn(params)
}

// GetAlarmLogsHandler interface for that can handle valid get alarm logs params
type GetAlarmLogsHandler interface {
	Handle(GetAlarmLogsParams) middleware.Responder
}

// NewGetAlarmLogs creates a new http.Handler for the get alarm logs operation
func NewGetAlarmLogs(ctx *middleware.Context, handler GetAlarmLogsHandler) *GetAlarmLogs {
	return &GetAlarmLogs{Context: ctx, Handler: handler}
}

/*GetAlarmLogs swagger:route GET /alarms/{id}/logs/ alarms getAlarmLogs

Get alarm logs

*/
type GetAlarmLogs struct {
	Context *middleware.Context
	Handler GetAlarmLogsHandler
}

func (o *GetAlarmLogs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAlarmLogsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
