// Code generated by go-swagger; DO NOT EDIT.

package alarms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"casa-api/models"
)

// GetAlarmLogsOKCode is the HTTP code returned for type GetAlarmLogsOK
const GetAlarmLogsOKCode int = 200

/*GetAlarmLogsOK Ok

swagger:response getAlarmLogsOK
*/
type GetAlarmLogsOK struct {

	/*
	  In: Body
	*/
	Payload models.Alarms `json:"body,omitempty"`
}

// NewGetAlarmLogsOK creates GetAlarmLogsOK with default headers values
func NewGetAlarmLogsOK() *GetAlarmLogsOK {
	return &GetAlarmLogsOK{}
}

// WithPayload adds the payload to the get alarm logs o k response
func (o *GetAlarmLogsOK) WithPayload(payload models.Alarms) *GetAlarmLogsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get alarm logs o k response
func (o *GetAlarmLogsOK) SetPayload(payload models.Alarms) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAlarmLogsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.Alarms, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetAlarmLogsDefault error

swagger:response getAlarmLogsDefault
*/
type GetAlarmLogsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAlarmLogsDefault creates GetAlarmLogsDefault with default headers values
func NewGetAlarmLogsDefault(code int) *GetAlarmLogsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetAlarmLogsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get alarm logs default response
func (o *GetAlarmLogsDefault) WithStatusCode(code int) *GetAlarmLogsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get alarm logs default response
func (o *GetAlarmLogsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get alarm logs default response
func (o *GetAlarmLogsDefault) WithPayload(payload *models.Error) *GetAlarmLogsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get alarm logs default response
func (o *GetAlarmLogsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAlarmLogsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
