// Code generated by go-swagger; DO NOT EDIT.

package alarms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ListAlarmLogsHandlerFunc turns a function with the right signature into a list alarm logs handler
type ListAlarmLogsHandlerFunc func(ListAlarmLogsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListAlarmLogsHandlerFunc) Handle(params ListAlarmLogsParams) middleware.Responder {
	return fn(params)
}

// ListAlarmLogsHandler interface for that can handle valid list alarm logs params
type ListAlarmLogsHandler interface {
	Handle(ListAlarmLogsParams) middleware.Responder
}

// NewListAlarmLogs creates a new http.Handler for the list alarm logs operation
func NewListAlarmLogs(ctx *middleware.Context, handler ListAlarmLogsHandler) *ListAlarmLogs {
	return &ListAlarmLogs{Context: ctx, Handler: handler}
}

/*ListAlarmLogs swagger:route GET /alarms/{id}/toggle/ alarms listAlarmLogs

List togglings

*/
type ListAlarmLogs struct {
	Context *middleware.Context
	Handler ListAlarmLogsHandler
}

func (o *ListAlarmLogs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListAlarmLogsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
