// Code generated by go-swagger; DO NOT EDIT.

package alarms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ListAlarmsHandlerFunc turns a function with the right signature into a list alarms handler
type ListAlarmsHandlerFunc func(ListAlarmsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListAlarmsHandlerFunc) Handle(params ListAlarmsParams) middleware.Responder {
	return fn(params)
}

// ListAlarmsHandler interface for that can handle valid list alarms params
type ListAlarmsHandler interface {
	Handle(ListAlarmsParams) middleware.Responder
}

// NewListAlarms creates a new http.Handler for the list alarms operation
func NewListAlarms(ctx *middleware.Context, handler ListAlarmsHandler) *ListAlarms {
	return &ListAlarms{Context: ctx, Handler: handler}
}

/*ListAlarms swagger:route GET /alarms alarms listAlarms

Gets all alarms

*/
type ListAlarms struct {
	Context *middleware.Context
	Handler ListAlarmsHandler
}

func (o *ListAlarms) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListAlarmsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
