// Code generated by go-swagger; DO NOT EDIT.

package alarms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ToggleAlarmHandlerFunc turns a function with the right signature into a toggle alarm handler
type ToggleAlarmHandlerFunc func(ToggleAlarmParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ToggleAlarmHandlerFunc) Handle(params ToggleAlarmParams) middleware.Responder {
	return fn(params)
}

// ToggleAlarmHandler interface for that can handle valid toggle alarm params
type ToggleAlarmHandler interface {
	Handle(ToggleAlarmParams) middleware.Responder
}

// NewToggleAlarm creates a new http.Handler for the toggle alarm operation
func NewToggleAlarm(ctx *middleware.Context, handler ToggleAlarmHandler) *ToggleAlarm {
	return &ToggleAlarm{Context: ctx, Handler: handler}
}

/*ToggleAlarm swagger:route POST /alarms/{id}/toggle/ alarms toggleAlarm

Toggle the alarm

*/
type ToggleAlarm struct {
	Context *middleware.Context
	Handler ToggleAlarmHandler
}

func (o *ToggleAlarm) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewToggleAlarmParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
