// Code generated by go-swagger; DO NOT EDIT.

package alerts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AddAlertHandlerFunc turns a function with the right signature into a add alert handler
type AddAlertHandlerFunc func(AddAlertParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddAlertHandlerFunc) Handle(params AddAlertParams) middleware.Responder {
	return fn(params)
}

// AddAlertHandler interface for that can handle valid add alert params
type AddAlertHandler interface {
	Handle(AddAlertParams) middleware.Responder
}

// NewAddAlert creates a new http.Handler for the add alert operation
func NewAddAlert(ctx *middleware.Context, handler AddAlertHandler) *AddAlert {
	return &AddAlert{Context: ctx, Handler: handler}
}

/*AddAlert swagger:route POST /alarms/{alarmId}/alerts/{id} alerts addAlert

Alert about something

*/
type AddAlert struct {
	Context *middleware.Context
	Handler AddAlertHandler
}

func (o *AddAlert) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddAlertParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
