// Code generated by go-swagger; DO NOT EDIT.

package alerts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"casa-api/models"
)

// ListAlertsByIDOKCode is the HTTP code returned for type ListAlertsByIDOK
const ListAlertsByIDOKCode int = 200

/*ListAlertsByIDOK Ok

swagger:response listAlertsByIdOK
*/
type ListAlertsByIDOK struct {

	/*
	  In: Body
	*/
	Payload models.Alerts `json:"body,omitempty"`
}

// NewListAlertsByIDOK creates ListAlertsByIDOK with default headers values
func NewListAlertsByIDOK() *ListAlertsByIDOK {
	return &ListAlertsByIDOK{}
}

// WithPayload adds the payload to the list alerts by Id o k response
func (o *ListAlertsByIDOK) WithPayload(payload models.Alerts) *ListAlertsByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list alerts by Id o k response
func (o *ListAlertsByIDOK) SetPayload(payload models.Alerts) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAlertsByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.Alerts, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*ListAlertsByIDDefault error

swagger:response listAlertsByIdDefault
*/
type ListAlertsByIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListAlertsByIDDefault creates ListAlertsByIDDefault with default headers values
func NewListAlertsByIDDefault(code int) *ListAlertsByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &ListAlertsByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list alerts by Id default response
func (o *ListAlertsByIDDefault) WithStatusCode(code int) *ListAlertsByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list alerts by Id default response
func (o *ListAlertsByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list alerts by Id default response
func (o *ListAlertsByIDDefault) WithPayload(payload *models.Error) *ListAlertsByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list alerts by Id default response
func (o *ListAlertsByIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAlertsByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
