// Code generated by go-swagger; DO NOT EDIT.

package alerts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"casa/src/server/models"
)

// ListAlertsForAlarmOKCode is the HTTP code returned for type ListAlertsForAlarmOK
const ListAlertsForAlarmOKCode int = 200

/*ListAlertsForAlarmOK Ok

swagger:response listAlertsForAlarmOK
*/
type ListAlertsForAlarmOK struct {

	/*
	  In: Body
	*/
	Payload models.Alerts `json:"body,omitempty"`
}

// NewListAlertsForAlarmOK creates ListAlertsForAlarmOK with default headers values
func NewListAlertsForAlarmOK() *ListAlertsForAlarmOK {
	return &ListAlertsForAlarmOK{}
}

// WithPayload adds the payload to the list alerts for alarm o k response
func (o *ListAlertsForAlarmOK) WithPayload(payload models.Alerts) *ListAlertsForAlarmOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list alerts for alarm o k response
func (o *ListAlertsForAlarmOK) SetPayload(payload models.Alerts) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAlertsForAlarmOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.Alerts, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*ListAlertsForAlarmDefault error

swagger:response listAlertsForAlarmDefault
*/
type ListAlertsForAlarmDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListAlertsForAlarmDefault creates ListAlertsForAlarmDefault with default headers values
func NewListAlertsForAlarmDefault(code int) *ListAlertsForAlarmDefault {
	if code <= 0 {
		code = 500
	}

	return &ListAlertsForAlarmDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list alerts for alarm default response
func (o *ListAlertsForAlarmDefault) WithStatusCode(code int) *ListAlertsForAlarmDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list alerts for alarm default response
func (o *ListAlertsForAlarmDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list alerts for alarm default response
func (o *ListAlertsForAlarmDefault) WithPayload(payload *models.Error) *ListAlertsForAlarmDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list alerts for alarm default response
func (o *ListAlertsForAlarmDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAlertsForAlarmDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
