// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ListOfDevicesHandlerFunc turns a function with the right signature into a list of devices handler
type ListOfDevicesHandlerFunc func(ListOfDevicesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListOfDevicesHandlerFunc) Handle(params ListOfDevicesParams) middleware.Responder {
	return fn(params)
}

// ListOfDevicesHandler interface for that can handle valid list of devices params
type ListOfDevicesHandler interface {
	Handle(ListOfDevicesParams) middleware.Responder
}

// NewListOfDevices creates a new http.Handler for the list of devices operation
func NewListOfDevices(ctx *middleware.Context, handler ListOfDevicesHandler) *ListOfDevices {
	return &ListOfDevices{Context: ctx, Handler: handler}
}

/*ListOfDevices swagger:route GET /devices devices listOfDevices

List of added devices

*/
type ListOfDevices struct {
	Context *middleware.Context
	Handler ListOfDevicesHandler
}

func (o *ListOfDevices) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListOfDevicesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
