// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewListOfDevicesParams creates a new ListOfDevicesParams object
// with the default values initialized.
func NewListOfDevicesParams() ListOfDevicesParams {
	var ()
	return ListOfDevicesParams{}
}

// ListOfDevicesParams contains all the bound params for the list of devices operation
// typically these are obtained from a http.Request
//
// swagger:parameters listOfDevices
type ListOfDevicesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *ListOfDevicesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
