// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"casa/src/server/models"
)

// ListOfDevicesOKCode is the HTTP code returned for type ListOfDevicesOK
const ListOfDevicesOKCode int = 200

/*ListOfDevicesOK ok

swagger:response listOfDevicesOK
*/
type ListOfDevicesOK struct {

	/*
	  In: Body
	*/
	Payload models.Devices `json:"body,omitempty"`
}

// NewListOfDevicesOK creates ListOfDevicesOK with default headers values
func NewListOfDevicesOK() *ListOfDevicesOK {
	return &ListOfDevicesOK{}
}

// WithPayload adds the payload to the list of devices o k response
func (o *ListOfDevicesOK) WithPayload(payload models.Devices) *ListOfDevicesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list of devices o k response
func (o *ListOfDevicesOK) SetPayload(payload models.Devices) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListOfDevicesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.Devices, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*ListOfDevicesDefault error

swagger:response listOfDevicesDefault
*/
type ListOfDevicesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListOfDevicesDefault creates ListOfDevicesDefault with default headers values
func NewListOfDevicesDefault(code int) *ListOfDevicesDefault {
	if code <= 0 {
		code = 500
	}

	return &ListOfDevicesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list of devices default response
func (o *ListOfDevicesDefault) WithStatusCode(code int) *ListOfDevicesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list of devices default response
func (o *ListOfDevicesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list of devices default response
func (o *ListOfDevicesDefault) WithPayload(payload *models.Error) *ListOfDevicesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list of devices default response
func (o *ListOfDevicesDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListOfDevicesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
