// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// AddAlert add alert
// swagger:model addAlert

type AddAlert struct {

	// description
	Description string `json:"description,omitempty"`

	// short description
	ShortDescription string `json:"shortDescription,omitempty"`
}

/* polymorph addAlert description false */

/* polymorph addAlert shortDescription false */

// Validate validates this add alert
func (m *AddAlert) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *AddAlert) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddAlert) UnmarshalBinary(b []byte) error {
	var res AddAlert
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
