// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Alarm alarm
// swagger:model alarm

type Alarm struct {

	// continous
	Continous bool `json:"continous,omitempty"`

	// date
	Date strfmt.DateTime `json:"date,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// Array of serial numbers
	Devices []string `json:"devices"`

	// id
	ID string `json:"id,omitempty"`

	// motion detection
	MotionDetection bool `json:"motionDetection,omitempty"`

	// on
	On bool `json:"on,omitempty"`

	// sms
	Sms *Sms `json:"sms,omitempty"`
}

/* polymorph alarm continous false */

/* polymorph alarm date false */

/* polymorph alarm description false */

/* polymorph alarm devices false */

/* polymorph alarm id false */

/* polymorph alarm motionDetection false */

/* polymorph alarm on false */

/* polymorph alarm sms false */

// Validate validates this alarm
func (m *Alarm) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDevices(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateSms(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Alarm) validateDevices(formats strfmt.Registry) error {

	if swag.IsZero(m.Devices) { // not required
		return nil
	}

	return nil
}

func (m *Alarm) validateSms(formats strfmt.Registry) error {

	if swag.IsZero(m.Sms) { // not required
		return nil
	}

	if m.Sms != nil {

		if err := m.Sms.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("sms")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Alarm) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Alarm) UnmarshalBinary(b []byte) error {
	var res Alarm
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
