// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DiscoveredDevice discovered device
// swagger:model discoveredDevice

type DiscoveredDevice struct {

	// address
	Address string `json:"address,omitempty"`

	// last discovered
	LastDiscovered strfmt.DateTime `json:"lastDiscovered,omitempty"`

	// model
	Model string `json:"model,omitempty"`

	// model number
	ModelNumber string `json:"modelNumber,omitempty"`

	// serial number
	SerialNumber string `json:"serialNumber,omitempty"`

	// status
	Status *DeviceStatus `json:"status,omitempty"`
}

/* polymorph discoveredDevice address false */

/* polymorph discoveredDevice lastDiscovered false */

/* polymorph discoveredDevice model false */

/* polymorph discoveredDevice modelNumber false */

/* polymorph discoveredDevice serialNumber false */

/* polymorph discoveredDevice status false */

// Validate validates this discovered device
func (m *DiscoveredDevice) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatus(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DiscoveredDevice) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if m.Status != nil {

		if err := m.Status.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("status")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DiscoveredDevice) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DiscoveredDevice) UnmarshalBinary(b []byte) error {
	var res DiscoveredDevice
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
