// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Sms sms notification
// swagger:model sms

type Sms struct {

	// from number
	FromNumber string `json:"fromNumber,omitempty"`

	// Number of minutes between sms if alerts keep repeating.
	Interval float64 `json:"interval,omitempty"`

	// Array of mobile numbers
	MobileNumbers []string `json:"mobileNumbers"`

	// password
	Password string `json:"password,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

/* polymorph sms fromNumber false */

/* polymorph sms interval false */

/* polymorph sms mobileNumbers false */

/* polymorph sms password false */

/* polymorph sms username false */

// Validate validates this sms
func (m *Sms) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMobileNumbers(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Sms) validateMobileNumbers(formats strfmt.Registry) error {

	if swag.IsZero(m.MobileNumbers) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Sms) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Sms) UnmarshalBinary(b []byte) error {
	var res Sms
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
